### ISSUE TITLE
SEGV when specify colorize option

### ISSUE THREAD

**Issue by muranoya** [muranoya/tkgrep#1]
`tkgrep -RG futex linux-4.15`

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f52556b6801 in __GI_abort () at abort.c:79
#2  0x00007f52560a98b7 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f52560afa06 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f52560afa41 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x000000000040553b in __clang_call_terminate ()
#6  0x0000000000405112 in print_result (filename=..., c=..., file_content=..., match_lines=...) at src/main.cpp:117
#7  tkgrep_r (Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
filename=, c=...) at src/main.cpp:358
#8  0x0000000000403e52 in tkgrep_r (filename=..., c=...) at src/main.cpp:329
#9  0x0000000000403e52 in tkgrep_r (filename=..., c=...) at src/main.cpp:329
#10 0x0000000000403e52 in tkgrep_r (filename=..., c=...) at src/main.cpp:329
#11 0x0000000000403e52 in tkgrep_r (filename=..., c=...) at src/main.cpp:329
#12 0x0000000000403e52 in tkgrep_r (filename=..., c=...) at src/main.cpp:329
#13 0x0000000000403e52 in tkgrep_r (filename=..., c=...) at src/main.cpp:329
#14 0x000000000040388b in main (argc=<optimized out>, argv=0x7fff57ba9668) at src/main.cpp:375
```

**Comment by muranoya** [comment]
resolved.
